apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: redis:alpine3.19
          command: ['redis-server', '--requirepass', '$(REDIS_PASSWORD)']
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pok-secrets
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    app: cache
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: admin
      port: 8001
      targetPort: 8001
  type: ClusterIP
