name: Deploy

on:
  push:
    paths:
      - 'src/**'
      - 'db/**'
      - 'package*.json'
      - 'drizzle.config.ts'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/release.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: Copy files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./docker-compose.yml
          remote: /pok/docker-compose.yml
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: garygrossgarten/github-action-scp@release
        with:
          local: ./drizzle.config.ts
          remote: /pok/docker-compose.yml
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: garygrossgarten/github-action-scp@release
        with:
          local: ./db
          remote: /pok/db
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: garygrossgarten/github-action-scp@release
        with:
          local: ./package.json
          remote: /pok/package.json
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: install drizzle-kit
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /pok
            npm update drizzle-kit

      - name: Create a .env file on the server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            touch .env
            echo POSTGRES_HOST=localhost >> /pok/.env
            echo POSTGRES_DB="${{ secrets.POSTGRES_DB }}" >> /pok/.env
            echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}" >> /pok/.env
            echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> /pok/.env
            history -c
            history -w

      - name: stop the api container
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /pok 
            docker compose stop api

      - name: push migrations to Database
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /pok
            npm run db:push

      - name: stop the api container
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /pok 
            docker compose up --pull always -d
