name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0
    branches:
      - main

env:
  DOCKER_USERNAME: 'dofer123'
  IMAGE_NAME: 'pok'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Release
        id: get_release
        run: |
          REPO="doper1/POK"  
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r .tag_name)
          echo "Latest Release: $LATEST_RELEASE"
          echo "::set-output name=latest_release::$LATEST_RELEASE"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get_release.outputs.latest_release }}
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
