name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  DU: 'dofer123'
  IP: 'pok'
  II: 'imagen'

jobs:
  release:
    if: ${{ !startsWith(github.head_ref, 'release-please') }}
    runs-on: ubuntu-latest
    outputs:
      pok--release_created: ${{ steps.release-please.outputs.pok--release_created}}
      pok-version: '${{ steps.release-please.outputs.pok--major }}.${{ steps.release-please.outputs.pok--minor }}.${{ steps.release-please.outputs.pok--patch }}'
      imagen--release_created: ${{ steps.release-please.outputs.imagen--release_created}}
      imagen-version: '${{ steps.release-please.outputs.imagen--major }}.${{ steps.release-please.outputs.imagen--minor }}.${{ steps.release-please.outputs.imagen--patch }}'
    steps:
      - name: Create a semantic release based on new commits
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.POK_PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DU }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Pok
        if: ${{ steps.release-please.outputs.pok--release_created }}
        uses: docker/build-push-action@v6
        with:
          context: ./pok
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.DU }}/${{ env.IP }}:${{ steps.release-please.outputs.pok-version }}
            ${{ env.DU }}/${{ env.IP }}:latest
          cache-from: type=gha,scope=pok
          cache-to: type=gha,scope=pok

      - name: Build and push Imagen
        if: ${{ steps.release-please.outputs.imagen--release_created }}
        uses: docker/build-push-action@v6
        with:
          context: ./Imagen
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.DU }}/${{ env.II }}:${{ steps.release-please.outputs.imagen-version }}
            ${{ env.DU }}/${{ env.II }}:latest
          cache-from: type=gha,scope=imagen
          cache-to: type=gha,scope=imagen

  call-deploy-pok:
    if: ${{ needs.release.outputs.pok--release_created }}
    needs:
      - release

    uses: ./.github/workflows/deploy_pok.yml
    secrets: inherit

  call-deploy-imagen:
    if: ${{ needs.release.outputs.imagen--release_created }}
    needs:
      - release

    uses: ./.github/workflows/deploy_imagen.yml
    secrets: inherit
