name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  DU: 'dofer123'
  IP: 'pok'
  II: 'imagen'

jobs:
  release:
    if: ${{ !startsWith(github.head_ref, 'release-please') }}
    runs-on: ubuntu-latest
    outputs:
      pok--release_created: ${{ steps.release-please.outputs.pok--release_created}}
      pok-version: '${{ steps.release-please.outputs.pok--major }}.${{ steps.release-please.outputs.pok--minor }}.${{ steps.release-please.outputs.pok--patch }}'
      imagen--release_created: ${{ steps.release-please.outputs.imagen--release_created}}
      imagen-version: '${{ steps.release-please.outputs.imagen--major }}.${{ steps.release-please.outputs.imagen--minor }}.${{ steps.release-please.outputs.imagen--patch }}'
    steps:
      - name: Create a semantic release based on new commits
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.POK_PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build-and-push:
    runs-on: ${{ matrix.host }}
    needs: release
    strategy:
      matrix:
        include:
          - host: ubuntu-latest
            platform: linux/amd64
            target: x86_64
          - host: self-hosted
            platform: linux/arm64/v8
            target: aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DU }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push Pok
        if: ${{ needs.release.outputs.pok--release_created }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.IP }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.DU }}/${{ env.IP }}:${{ needs.release.outputs.pok-version }}-${{ matrix.target }}
            ${{ env.DU }}/${{ env.IP }}:latest-${{ matrix.target }}
          cache-from: type=registry,ref=${{ env.DU }}/${{ env.IP }}:buildcache-${{ matrix.target }}
          cache-to: type=registry,ref=${{ env.DU }}/${{ env.IP }}:buildcache-${{ matrix.target }},mode=max

      - name: Docker build and push Imagen
        if: ${{ needs.release.outputs.imagen--release_created }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.II }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.DU }}/${{ env.II }}:${{ needs.release.outputs.imagen-version }}-${{ matrix.target }}
            ${{ env.DU }}/${{ env.II }}:latest-${{ matrix.target }}
          cache-from: type=registry,ref=${{ env.DU }}/${{ env.II }}:buildcache-${{ matrix.target }}
          cache-to: type=registry,ref=${{ env.DU }}/${{ env.II }}:buildcache-${{ matrix.target }},mode=max
          build-args: |
            TARGET=${{ matrix.target }}

  call-deploy-pok:
    if: ${{ needs.release.outputs.pok--release_created }}
    needs:
      - release
      - build-and-push

    uses: ./.github/workflows/deploy_pok.yml
    secrets: inherit

  call-deploy-imagen:
    if: ${{ needs.release.outputs.imagen--release_created }}
    needs:
      - release
      - build-and-push

    uses: ./.github/workflows/deploy_imagen.yml
    secrets: inherit
