name: Release

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  DOCKER_USERNAME: 'dofer123'
  IMAGE_NAME: 'pok'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create a semantic release based on new commits
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.POK_PAT }}
          release-type: node

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker versioned docker image
        uses: docker/build-push-action@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}

      - name: Build and push latest Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
