name: Test pok

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'imagen/**'
      - 'docs/**'

env:
  DOCKER_USERNAME: 'dofer123'
  IMAGE_NAME: 'pok'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: set environment variables
        run: |
          echo POSTGRES_HOST=localhost > /pok/.env
          echo POSTGRES_DB="${{ secrets.POSTGRES_DB }}" >> /pok/.env
          echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}" >> /pok/.env
          echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> /pok/.env
          echo OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" >> /pok/.env

      - name: start db
        run: docker compose up db -d

      - name: Install dependencies, lint test and tests
        run: |
          cd pok
          npm ci
          npm run lint
          npm run test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker multi-platform build test
        uses: docker/build-push-action@v6
        with:
          context: ./pok
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:test
