name: Test imagen

on:
  pull_request:
    branches:
      - main
    paths:
      - 'imagen/**'

env:
  DOCKER_USERNAME: 'dofer123'
  IMAGE_NAME: 'imagen'
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set environment variables
        run: |
          echo POSTGRES_HOST=localhost > .env
          echo POSTGRES_DB="${{ secrets.POSTGRES_DB }}" >> .env
          echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}" >> .env
          echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> .env
          cp .env ./imagen/.env

      - name: start db
        run: docker compose up db -d

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: |
          cd imagen
          cargo test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement=mount

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-buildx-

      - name: Multi-platform Docker build
        uses: docker/build-push-action@v6
        with:
          context: ./imagen
          platforms: linux/amd64,linux/arm64/v8
          push: false
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:test
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
