name: Visualize project

on: workflow_call

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: 'docs/diagram.svg'
          root_path: 'src/'
          excluded_paths: '__tests__'
