name: Visualize project

on:
  workflow_dispatch:

jobs:
  get_data:
    if: ${{ !startsWith(github.head_ref, 'release-please') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update diagram of Pok
        uses: githubocto/repo-visualizer@main
        with:
          output_file: 'docs/diagrams/diagram_pok.svg'
          root_path: '/pok/src/'
          excluded_paths: '__tests__'

      - name: Update diagram of Imagen
        uses: githubocto/repo-visualizer@main
        with:
          output_file: 'docs/diagrams/diagram_imagen.svg'
          root_path: '/imagen/src/'
